//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBDKarty
{
    using System;
    using System.Collections.Generic;
    
    public partial class Karty_Talia
    {
        public int ID_K_T { get; set; }
        public int Ilosc_Sztuk { get; set; }
        public Nullable<int> ID_Karty { get; set; }
        public int ID_Talii { get; set; }
    
        public virtual Karty Karty { get; set; }
        public virtual Talia Talia { get; set; }
    }
}
