//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBDKarty
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Kartyv1Entities : DbContext
    {
        public Kartyv1Entities()
            : base("name=Kartyv1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Gracz> Gracz { get; set; }
        public virtual DbSet<Karty> Karty { get; set; }
        public virtual DbSet<Karty_Talia> Karty_Talia { get; set; }
        public virtual DbSet<Kreatury> Kreatury { get; set; }
        public virtual DbSet<Mana> Mana { get; set; }
        public virtual DbSet<Planeswalker> Planeswalker { get; set; }
        public virtual DbSet<Statystyka> Statystyka { get; set; }
        public virtual DbSet<Talia> Talia { get; set; }
    }
}
