//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBDKarty
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statystyka
    {
        public int ID_Statystyki { get; set; }
        public Nullable<int> Wygrane { get; set; }
        public Nullable<int> Przegrane { get; set; }
        public Nullable<int> Remisy { get; set; }
        public int ID_Gracza { get; set; }
    
        public virtual Gracz Gracz { get; set; }
    }
}
