//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBDKarty
{
    using System;
    using System.Collections.Generic;
    
    public partial class Talia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Talia()
        {
            this.Gracz = new HashSet<Gracz>();
            this.Karty_Talia = new HashSet<Karty_Talia>();
        }
    
        public int ID_Talii { get; set; }
        public string Nazwa_Talii { get; set; }
        public Nullable<int> Ilosc_Kart { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gracz> Gracz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Karty_Talia> Karty_Talia { get; set; }
    }
}
